version: "3.8"
services:
  service_bcpp_db:
    image: postgres
    container_name: container_bcpp_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata: